config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :primary_item_lists

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'homes#index'
  get 'setting', to: 'homes#setting' # setting_path

  resources :spends
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :logged_in_user, only: %i[setting]
  rescue_from Banken::NotAuthorizedError, with: :user_not_authorized

  def index
    authorize!

    @this_month_spends = current_spends.this_month
    @prev_month_spends = current_spends.prev_month
    @sum_this_month_spends_price = @this_month_spends.sum(:price)
    @sum_prev_month_spends_price = @prev_month_spends.sum(:price)
    @primary_item_lists = current_primary_item_lists.order(:id)
    @sum_spends_target_value = @primary_item_lists.sum(:spend_target_value)
  end

  def setting; end

  private

  def user_not_authorized
    render :index
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.slim
- provide(:title, 'トップ')
- if user_signed_in?
  p ログインしてる人:#{ current_user.email }
  div.index-table
    h2 今月の支出合計
    table 
      tbody 
        tr 
          th 今月の支出合計
          td.td-spend = @sum_this_month_spends_price.to_s(:delimited)
    h2 詳細
    table 
      thead 
        tr 
          th 項目名
          th 先月の支出
          th 今月の支出合計
          th 今月の支出目標
          th 目標値との比較
      tbody 
        tr 
          th 合計
          td.td-spend = @sum_prev_month_spends_price.to_s(:delimited)
          td.td-spend = @sum_this_month_spends_price.to_s(:delimited)
          td.td-spend = @sum_spends_target_value.to_s(:delimited)
          td.td-spend = (@sum_spends_target_value - @sum_this_month_spends_price).to_s(:delimited)
        - @primary_item_lists.each do |primary_item_list|
          - sum_this_month_spends_primary_item_list_id = @this_month_spends.where(primary_item_list_id: primary_item_list.id).sum(:price)
          tr 
            th = primary_item_list.name
            td.td-spend = @prev_month_spends.where(primary_item_list_id: primary_item_list.id).sum(:price).to_s(:delimited)
            td.td-spend = sum_this_month_spends_primary_item_list_id.to_s(:delimited)
            td.td-spend = primary_item_list.spend_target_value.to_s(:delimited)
            td.td-spend = (primary_item_list.spend_target_value - sum_this_month_spends_primary_item_list_id).to_s(:delimited)

- else
  div.main-image
    = image_tag 'home_top.jpg'

div.site-guidance
  h3 このサイトの使い方
  h4 登録など
  p 右上の新規登録から登録します。お使いのメールアドレスと任意のパスワードを入力してください。
  h4 ログイン･ログアウト
  p サイト右上の項目から行います。
  h4 ログイン後のトップページ
  p 今月の支出の合計などが見られます。
  h4 支出の記録
  p ログインすると、[トップ、支出、設定]といったメニューが表示されます。
  p その中の支出を選択すると、支出の記録や一覧の確認、検索などが行なえます。
  h4 各種設定
  p メニューの中の設定を選択すると、アカウント情報の変更、削除、支出の大項目編集、支出の目標値設定などが行なえます。

h3 作る予定の機能
ul 
  li 収入を入力できるようにする、収入と支出を比較できるようにする
  li ユーザー登録時のメールアドレス認証を追加する

app/views/homes/setting.html.slim
- provide(:title, '設定')

h2 各種設定

ul.list
  li.list-item = link_to 'アカウント情報変更、削除', edit_user_registration_path
  li.list-item = link_to '大項目一覧、追加、編集、削除(毎月の支出目標の設定を含む)', primary_item_lists_path

  