config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :primary_item_lists

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'homes#index'
  get 'setting', to: 'homes#setting' # setting_path

  resources :spends
end

app/models/primary_item_list.rb
# == Schema Information
#
# Table name: primary_item_lists
#
#  id                               :bigint           not null, primary key
#  initial_flag(初期値の判定)       :boolean          default(FALSE), not null
#  name(大項目)                     :string           not null
#  spend_target_value(支出の目標値) :integer          default(0), not null
#  created_at                       :datetime         not null
#  updated_at                       :datetime         not null
#  user_id(userと紐づけ)            :integer
#
# Indexes
#
#  index_primary_item_lists_on_name_and_user_id  (name,user_id) UNIQUE
#
class PrimaryItemList < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :initial_flag, inclusion: { in: [true, false] }
  validates :spend_target_value, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 999999999 }

  has_many :spends, dependent: :nullify
  belongs_to :user
end

app/controllers/primary_item_lists_controller.rb
class PrimaryItemListsController < ApplicationController
  before_action :logged_in_user
  rescue_from Banken::NotAuthorizedError, with: :user_not_authorized

  def index
    @primary_item_lists = current_primary_item_lists.order(:id)
    @primary_item_list = current_primary_item_lists.new
  end

  def create
    @primary_item_list = current_primary_item_lists.new(primary_item_list_params)
    begin
      @primary_item_list.save!
      redirect_to primary_item_lists_path, flash: { success: t('success_message') }
    rescue StandardError
      @primary_item_lists = current_primary_item_lists.order(:id)
      flash.now[:danger] = @primary_item_list.error_message
      render :index
    end
  end

  def destroy
    @primary_item_list = PrimaryItemList.find(params[:id])
    authorize! @primary_item_list
    @primary_item_list.destroy
    redirect_to primary_item_lists_path, flash: { success: t('destroy_message') }
  end

  def update
    @primary_item_list = PrimaryItemList.find(params[:id])
    authorize! @primary_item_list
    begin
      @primary_item_list.update!(primary_item_list_params)
      redirect_to primary_item_lists_path, flash: { success: t('success_message') }
    rescue StandardError
      flash.now[:danger] = @primary_item_list.error_message
      render :edit
    end
  end

  def edit
    @primary_item_list = PrimaryItemList.find(params[:id])
    authorize! @primary_item_list
  end

  private

  def primary_item_list_params
    params.require(:primary_item_list).permit(:name, :user_id, :spend_target_value)
  end

  def user_not_authorized
    redirect_to root_path, flash: { alert: '無効なURLです。' }
  end
end

app/helpers/primary_item_lists_helper.rb
module PrimaryItemListsHelper
end

app/views/primary_item_lists/_form.html.slim
- flash.each do |message_type, message|
  div class="alert alert-#{message_type} alert-dismissible fade show"
    = message
    button.btn-close[type='button' data-bs-dismiss='alert' aria-label='Close']
= form_with class: 'form', model: @primary_item_list, local: true do |f|
  - if @primary_item_list.initial_flag
    p = t('name')
    p = @primary_item_list.name
  - else
    .form-group
      = f.label :name
        = t('name')
        span.badge.bg-danger.ms-1
          | 必須
      br
      = f.text_field :name, class: 'txt-box'
  .form-group 
    = f.label :spend_target_value
      = t('spend_target_value')
      span.badge.bg-danger.ms-1
        | 必須
    br
    = f.text_field :spend_target_value, class: 'txt-box'
  = f.submit nil, class: 'submit'

app/views/primary_item_lists/edit.html.slim
- provide(:title, '大項目編集')
h2 大項目編集

= render partial: 'form'

app/views/primary_item_lists/index.html.slim
- provide(:title, '大項目一覧')
div.form-box
  h2.h2-long 大項目一覧、追加、編集、削除
  = render partial: 'form'
div.index-table
  table.short-table
    thead
      tr 
        th = t('name')
        th = t('spend_target_value')
        th = t('edit')
        th = t('destroy')
    tbody 
      - @primary_item_lists.each do |primary_item_list|
        tr 
          td = primary_item_list.name
          td.td-spend = primary_item_list.spend_target_value.to_s(:delimited)
          td.td-edit
            = link_to t('edit'), edit_primary_item_list_path(primary_item_list)
          td.td-destroy 
            - unless primary_item_list.initial_flag 
              = link_to t('destroy'), primary_item_list, method: :delete, data:{confirm: '同じ名前の大項目は全て空になってしまいますが、本当に削除してもよいですか?'}