config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :primary_item_lists

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'homes#index'
  get 'setting', to: 'homes#setting' # setting_path

  resources :spends
end

app/models/spend.rb
# == Schema Information
#
# Table name: spends
#
#  id                                              :bigint           not null, primary key
#  content(内容)                                   :string
#  price(金額)                                     :integer          not null
#  created_at                                      :datetime         not null
#  updated_at                                      :datetime         not null
#  primary_item_list_id(primary_item_listと紐づけ) :integer          not null
#  user_id(userと紐づけ)                           :integer          not null
#
class Spend < ApplicationRecord
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 999999999 }
  validates :user_id, presence: true

  belongs_to :user
  belongs_to :primary_item_list

  # 今月のデータ取得
  scope :this_month, -> { where(created_at: Date.current.all_month) }

  # 先月のデータ取得
  scope :prev_month, -> { where(created_at: Date.current.prev_month.all_month) }
end

app/controllers/spends_controller.rb
class SpendsController < ApplicationController
  before_action :logged_in_user
  rescue_from Banken::NotAuthorizedError, with: :user_not_authorized

  def index
    primary_item_list_id = default_primaty_item_list_id
    @spend = current_spends.new(primary_item_list_id: primary_item_list_id)
    @primary_item_lists = current_primary_item_lists.order(:id)
    @q = current_spends.ransack(params[:q])
    @spends = target_spends
  end

  def create
    @spend = current_spends.new(spend_params)
    begin
      @spend.save!
      redirect_to spends_path, flash: { success: t('success_message') }
    rescue StandardError
      @q = current_spends.ransack(params[:q])
      @spends = target_spends
      @primary_item_lists = current_primary_item_lists.order(:id)
      flash.now[:danger] = @spend.error_message
      render :index
    end
  end

  def edit
    @spend = Spend.find(params[:id])
    authorize! @spend
    @spend.primary_item_list_id ||= default_primaty_item_list_id
    @primary_item_lists = current_primary_item_lists.order(:id)
  end

  def update
    @spend = Spend.find(params[:id])
    authorize! @spend
    begin
      @spend.update!(spend_params)
      redirect_to spends_path, flash: { success: t('update_message') }
    rescue StandardError
      @primary_item_lists = current_primary_item_lists.order(:id)
      flash.now[:danger] = @spend.error_message
      render :edit
    end
  end

  def destroy
    @spend = Spend.find(params[:id])
    authorize! @spend
    @spend.destroy
    redirect_to spends_path, flash: { success: t('destroy_message') }
  end

  private

  def spend_params
    params.require(:spend).permit(:content, :price, :primary_item_list_id, :user_id)
  end

  def default_primaty_item_list_id
    current_primary_item_lists.find_by(name: '未分類').id
  end

  def target_spends
    @q.result.includes(:primary_item_list).order(created_at: :desc).page(params[:page]).per(30)
  end

  def user_not_authorized
    redirect_to root_path, flash: { alert: '無効なURLです。' }
  end
end

app/helpers/spends_helper.rb
module SpendsHelper
end

app/views/spends/_form.html.slim
- flash.each do |message_type, message|
  div class="alert alert-#{message_type} alert-dismissible fade show"
    = message
    button.btn-close[type='button' data-bs-dismiss='alert' aria-label='Close']
= form_with class: 'form', model: @spend, local: true do |f|
  .form-group
    = f.label :primary_item_list_id
      = t('primary_item')
    br
    = f.collection_select :primary_item_list_id, @primary_item_lists, :id, :name, selected: @spend.primary_item_list_id
  .form-group
    = f.label :content
      = t('content')
    br
    = f.text_field :content, class: 'txt-box', placeholder: '例:パンとジュース'
  .form-group
    = f.label :price
      = t('price')
      span.badge.bg-danger.ms-1.rounded-pill
        | 必須
    br
    = f.text_field :price, class: "txt-box", placeholder: '最大9桁'
  = f.submit nil, class: 'submit'

app/views/spends/edit.html.slim
- provide(:title, '出費編集')
h2 出費編集
= render partial: 'form'

app/views/spends/index.html.slim
- provide(:title, '出費編集')
div.form-box
  h2 支出入力
  = render partial: 'form'
div.form-box
  h2 検索コーナー
  = search_form_for @q, class: 'form' do |f|
    .form-group
      p 大項目で検索(部分一致)
      = f.search_field :primary_item_list_name_cont, class: 'txt-box'
    .form-group
      p 期間指定で検索
      = f.date_field :created_at_gteq, include_blank: true, class: 'date-box'
      span ~
      = f.date_field :created_at_lteq_end_of_day, include_blank: true, class: 'date-box'
    = f.submit class: 'submit'
div.index-table
  h2 支出一覧
  div.kaminari
    = paginate @spends
    = page_entries_info @spends
  table
    thead
      tr 
        th = sort_link(@q, :created_at, t('created_at'))
        th = t('primary_item')
        th = t('content')
        th = sort_link(@q, :price, t('price'))
        th = t('edit')
        th = t('destroy')
    tbody 
      - @spends.each do |spend|
        tr
          td.td-created_at = spend.created_at.to_s(:datetime_jp)
          td.td-primary_item = spend.primary_item_list.try(:name)
          td = spend.content 
          td.td-spend = spend.price.to_s(:delimited)
          td.td-edit = link_to t('edit'), edit_spend_path(spend)
          td.td-destroy = link_to t('destroy'), spend, method: :delete, data:{confirm: '削除してもよいですか?'}